application: pyweb-ko
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /public
  static_dir: public

- url: /favicon.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon.ico

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
      
- url: .*
  script: main.py
